In [17]:
import os
import pickle
import numpy as np
import our_Wolpertinger

from our_Wolpertinger import Wolpertinger
from tqdm import tqdm

import sys
sys.path.append(os.path.join(os.getcwd(), 'Simulator'))
from WordCounting_Wolpertinger import WordCountingEnv

In [2]:
with open(f"./offline/random_wolpertinger_0.pkl", 'rb') as f:
    buffer = pickle.load(f)

In [11]:
s = buffer.sample(1)
state_dim = s[0].shape[-1]
action_dim = s[1].shape[-1]

In [12]:
model = Wolpertinger(state_dim, action_dim, n_machines=5, n_exe=20)

In [41]:
s = buffer.sample(1)
s

(tensor([[ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
           0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
           1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
           0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
           0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
           0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           1.,  0., 20., 20.]]),
 tensor([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
          1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0

In [43]:
s[1]

tensor([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
for i in tqdm(range(10000)):
    model.train(buffer)

100%|██████████| 10000/10000 [03:18<00:00, 50.35it/s]


In [60]:
def eval_policy(policy, eval_env, eval_episodes=1):
    avg_reward = 0.
    step_count = 0
    for _ in range(eval_episodes):
        state, done = eval_env.reset(), False
        while not done:
            action, _ = policy.select_action(np.array(state), noise=False)
            state, reward, done, _ = eval_env.step(action)
            print(reward)
            avg_reward += reward
            step_count += 1
            if step_count >= 10:
                break

    avg_reward /= eval_episodes

    print("---------------------------------------")
    print(f"Evaluation over {eval_episodes} episodes: {avg_reward:.3f} steps:{avg_reward/step_count:.3f}")
    print("---------------------------------------")
    return avg_reward

In [63]:
eval_env = WordCountingEnv(seed=101)

Building Topology
spout 2
WordCount 9
Database 9


/Users/xinyaoniu/.local/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [64]:
eval_policy(model, eval_env)

0.004275 collected with offset=-9957.25
-10003.853221
0.0 collected with offset=-10000.0
-10000.0


KeyboardInterrupt: 